# Generated by Django 5.2.17 on 2026-10-02 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=160)),
                ('goals', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('instruction', models.TextField()),
                ('definition', models.JSONField(default=dict)),
                ('ordinal', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('system_prompt', models.TextField()),
                ('tools', models.JSONField(default=list)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='aap.agent')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_mode', models.CharField(choices=[('LIVE_MODEL', 'Live Model'), ('DEMO_FALLBACK', 'Demo Fallback')], max_length=20)),
                ('status', models.CharField(default='preparing', max_length=20)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('error', models.JSONField(null=True)),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aap.agentversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_snapshot', models.JSONField(default=dict)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('verdict', models.CharField(max_length=20, null=True)),
                ('assertions', models.JSONField(default=list)),
                ('findings', models.JSONField(default=list)),
                ('evidence_complete', models.BooleanField(default=False)),
                ('final_response', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aap.evaluationrun')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aap.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='TraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
                ('tool', models.CharField(blank=True, max_length=40)),
                ('arguments', models.JSONField(default=dict)),
                ('success', models.BooleanField(null=True)),
                ('data', models.JSONField(default=dict)),
                ('error', models.JSONField(null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='aap.scenarioresult')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('agent', 'version'), name='agent_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('execution_mode__in', ['LIVE_MODEL', 'DEMO_FALLBACK'])), name='run_requires_execution_mode'),
        ),
        migrations.AddConstraint(
            model_name='scenarioresult',
            constraint=models.UniqueConstraint(fields=('run', 'scenario'), name='run_scenario_unique'),
        ),
        migrations.AddConstraint(
            model_name='traceevent',
            constraint=models.UniqueConstraint(fields=('result', 'sequence'), name='result_sequence_unique'),
        ),
    ]
